name: lin_player_server_adapters_uhd
description: UHD backend adapter overrides for LinPlayer.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  lin_player_core:
    path: ../lin_player_core
  lin_player_server_api:
    path: ../lin_player_server_api
  lin_player_server_adapters:
    path: ../lin_player_server_adapters

